### ISSUE TITLE
Design: Work on the Floating-Point Unit: Floating Point Adder

### ISSUE THREAD

**Issue by aubindetrez** [aubindetrez/implPower#16]
The Floating-Point Unit will perform more operations but here we focus on the Adder performance.

### Phase 1
- [ ] **Work in progress** Full review (In `Documentation/Core/FloatingPoint/...`) of existing opensource Floating-Point Adder
implementation and research papers.
- [ ] **Work in progress** Minimalistic MiniFloat8 Adder (Vanilla design), fully verified using a combinaison of functional
(Chisel-test) and formal methods.
- [ ] Improved version(s) of the MiniFloat8 Adder using Near/Far paths, verified using equivalence checking (yosys)
- [ ] Full documentation of the MiniFloat8 Adder, to explain concepts and attract contributors

### Phase 2
- [ ] MiniFloat16 Adder (Vanilla design), reuse some of the verification code from the MiniFloat8 version
- [ ] Compare edge-cases to existing implementation (like python IEEE compiant library...)
- [ ] Improved version(2) using Near/Far paths, verified using equivalence checking (yosys)

### Phase 3
- [ ] **Partial implementation ready** Implement a Single precision (32-bit) and Double (64-bit) Vanilla version, use formal and functional code from the previous
iterations for the verification
- [ ] Add Near/Far paths optimisation, run the same verification + equivalence checking
- [ ] Try different optimisations like new Near/Far path conditions ... (to be determined)
